# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Migration Guide
    url: blog/ros2-jazzy-migration/
    weight: 20
  - name: Docs
    url: docs/
    weight: 30
  - name: LinkedIn
    url: https://www.linkedin.com/in/pouya-shaterzadeh-b88426284/
    weight: 40
  - name: GitHub
    url: https://github.com/Pouya-Shaterzadeh/
    weight: 50

sidebar:
  - identifier: more
    name: Still need help?
    params:
      type: separator
    weight: 1
  - identifier: community
    name: "Community"
    pageRef: "/community"
    weight: 2
  - identifier: hugoDocs
    name: "Hugo Docs ↗"
    url: "https://docs.hugoblox.com"
    weight: 3
